---
title: "transition"
author: "Blublu"
date: "2025-03-10"
output: html_document
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(patchwork)
```


```{r}
df <- read.csv("../NLP/results/docs_topic_weights_reduce_outlier.csv")

df <- df %>%
  left_join(
    df %>% select(ID, assigned_topic) %>% rename(parent_ID = ID, parent_topic = assigned_topic),
    by = "parent_ID"
  )
```


```{r}
df_graph <- tibble()

for (i in 2:10){
  for (topic_n in 0:8){
    temp <- df %>%
      filter(gen == i) %>%
      filter(assigned_topic != -1) %>%
      filter(parent_topic == topic_n) %>%
      count(assigned_topic, sort = TRUE) %>%
      mutate(
        freq = round(n/sum(n), 2),
        received_topic = topic_n,
        gen = i
      ) %>%
      rename(topic = assigned_topic)
    df_graph <- bind_rows(df_graph, temp)
  }
}
```


```{r}
df_graph %>%
  group_by(received_topic, topic) %>%
  summarise(
    n = sum(n)
  ) %>%
  ungroup() %>%
  group_by(received_topic) %>%
  mutate(freq = n/sum(n)) %>%
  ggplot( aes(y = freq, x = topic, fill = as.factor(topic))) +
  geom_col() +
  geom_text(aes(label = n), vjust = -0.5) +
  facet_wrap(~received_topic) +
  labs(
    x = "",
    y = "transition probability",
    fill = "topic",
    title = "Transition probability over whole population"
  )
```

```{r}
topic_colors <- c(
  "0" = "#1f77b4",
  "1" = "#ff7f0e",
  "2" = "#2ca02c",
  "3" = "#d62728",
  "4" = "#9467bd",
  "5" = "#8c564b",
  "6" = "#e377c2",
  "7" = "#7f7f7f",
  "8" = "#4bc32f"
)

for (n_gen in 2:10) {
  
  p1 <- df_graph %>%
    filter(gen == n_gen) %>%
    ggplot( aes(y = freq, x = as.factor(topic), fill = as.factor(topic))) +
    geom_col() +
    facet_wrap(~received_topic) +
    scale_fill_manual(values = topic_colors) +
    labs(
      x = "",
      y = "transition probability",
      fill = "topic"
    )
  
  p2 <- df_graph %>%
    filter(gen == n_gen) %>%
    group_by(received_topic) %>%
    summarize(total_n = sum(n)) %>%
    ggplot(aes(x = as.factor(received_topic), y = total_n, fill = as.factor(received_topic))) +
    geom_col() +
    geom_text(aes(label = total_n), vjust = -0.5) +
    scale_fill_manual(values = topic_colors) +
    labs(
      x = "Topic received",
      y = "N",
      fill = "Topic"
    )
  
  p <- p1 + (p2 + plot_layout(guide = "keep")) + 
    plot_layout(guide = "collect") + 
    plot_annotation(paste("Generation:", n_gen))
  print(p)
  
}
```


```{r}
df_graph <- tibble()

for (i in 2:10){
  for (topic_n in 0:8){
    temp_low <- df %>%
      filter(gen == i) %>%
      filter(rank < 50) %>%
      filter(assigned_topic != -1) %>%
      filter(parent_topic == topic_n) %>%
      count(assigned_topic, sort = TRUE) %>%
      mutate(
        freq = round(n/sum(n), 2),
        received_topic = topic_n,
        gen = i,
        rank = "low"
      ) %>%
      rename(topic = assigned_topic)
    temp_high <- df %>%
      filter(gen == i) %>%
      filter(rank >= 50) %>%
      filter(assigned_topic != -1) %>%
      filter(parent_topic == topic_n) %>%
      count(assigned_topic, sort = TRUE) %>%
      mutate(
        freq = round(n/sum(n), 2),
        received_topic = topic_n,
        gen = i,
        rank = "high"
      ) %>%
      rename(topic = assigned_topic)
    temp <- bind_rows(temp_low, temp_high)
    df_graph <- bind_rows(df_graph, temp)
  }
}
```



```{r}
df_graph %>%
  filter(rank == "low") %>%
  group_by(received_topic, topic) %>%
  summarise(
    n = sum(n)
  ) %>%
  ungroup() %>%
  group_by(received_topic) %>%
  mutate(freq = n/sum(n)) %>%
  ggplot( aes(y = freq, x = topic, fill = as.factor(topic))) +
  geom_col() +
  geom_text(aes(label = n), vjust = -0.5) +
  facet_wrap(~received_topic) +
  labs(
    x = "",
    y = "transition probability",
    fill = "topic",
    title = "Transition probability over 'low' population"
  )

df_graph %>%
  filter(rank == "high") %>%
  group_by(received_topic, topic) %>%
  summarise(
    n = sum(n)
  ) %>%
  ungroup() %>%
  group_by(received_topic) %>%
  mutate(freq = n/sum(n)) %>%
  ggplot( aes(y = freq, x = topic, fill = as.factor(topic))) +
  geom_col() +
  geom_text(aes(label = n), vjust = -0.5) +
  facet_wrap(~received_topic) +
  labs(
    x = "",
    y = "transition probability",
    fill = "topic",
    title = "Transition probability over 'high' population"
  )
```


## Repartition topic / selectec topic

```{r}
temp_1 <- df %>%
  filter(gen > 1) %>%
  group_by(gen) %>%
  count(assigned_topic) %>%
  mutate(var = "old_gen_topic") %>%
  rename(topic = assigned_topic)

temp_2 <- df %>%
  filter(gen > 1) %>%
  group_by(gen) %>%
  count(parent_topic) %>%
  mutate(var = "selected_topic") %>%
  rename(topic = parent_topic)

df_graph <- bind_rows(temp_1, temp_2)
```


```{r}
df_graph %>%
  ggplot( aes(x = as.factor(topic), y = n, fill = var)) +
  geom_col(position="dodge") +
  facet_wrap(~gen) +
  labs(
    x = "topic",
    title = "Number of selected topic versus topic present in last gen"
  )
```













