---
title: "plotting"
author: "Blublu"
date: "2025-01-25"
output: html_document
---


```{r setup}
library(ggplot2)
library(tidyverse)
```


## ROBUSTNESS

Real value
```{r}
df <- read.csv("../results/robustness_check/results.csv")

df <- df %>%
  mutate(
    param = str_extract(run_name, "(?<=bertopic_-?)[^-]+")
  )

base_row <- df %>%
  filter(run_name == "base") %>%
  select(-param)
duplicated_row <- crossing(base_row, param = setdiff(df$param[!is.na(df$param)], "base"))

df <- df %>%
  filter(param != "base") %>%
  bind_rows(duplicated_row)

df
```


Main (and only plots)
```{r}
ggplot(df, aes(x = param, y = corr)) +
  geom_boxplot() +
  geom_jitter(aes(color = run_name)) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, by = .2),
    expand = c(0, 0)
  ) +
  theme_minimal() +
  labs(
    x = "",
    y = "Correlation",
    color = "Hyperparameter value"
  ) +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.line = element_line(colour = "black", size = .8),
    axis.ticks = element_line(colour = "black", size = .8),
    axis.ticks.length.x = unit(5, "pt"),
    axis.ticks.length.y = unit(7, "pt"),
    axis.text = element_text(size = 11, colour = "black", angle = 70, hjust = 1),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 16
    ),
    axis.title.y = element_text(
      margin = margin(r = 10),
      size = 16
    ),
    plot.margin = margin(15, 15, 10, 15)
  )

ggsave("../results/fig/robustness_corr.tiff", bg = "white",  width = 12, height = 6)
```

## TOPIC WEIGHT

```{r}
df <- read.csv("../results/docs_topic_weights.csv")
```


```{r}
cor.test(df$pl2_understanding, df$topic_2, method = "spearman")

res <- lm(formula = score_corrected ~ topic_2, data = df)
summary(res)

res <- lm(formula = pl2_understanding ~ topic_2, data = df)
summary(res)

res <- lm(formula = score_corrected ~ parent_topic_2,
  data = df %>% filter(gen > 1)
)
summary(res)

res <- lm(formula = pl2_understanding ~ parent_topic_2,
  data = df %>% filter(gen > 1)
)
summary(res)
```


## REDUCE OUTLIER

```{r}
df_reduce <- read.csv("../results/docs_topic_weights_reduce_outlier.csv")
df <- df <- read.csv("../results/docs_topic_weights.csv")
```

```{r}
cor.test(df$topic_2, df$pl2_understanding, method = "s")
cor.test(df_reduce$topic_2, df_reduce$pl2_understanding, method = "s")
```


## DUMP

similarity robustness check
```{r}
ggplot(df, aes(x = param, y = similarity)) +
  geom_boxplot() +
  geom_jitter(aes(color = run_name)) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, by = .2),
    expand = c(0, 0)
  ) +
  theme_minimal() +
  labs(
    x = "",
    y = "Similarity",
    color = "Hyperparameter value"
  ) +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.line = element_line(colour = "black", size = .8),
    axis.ticks = element_line(colour = "black", size = .8),
    axis.ticks.length.x = unit(5, "pt"),
    axis.ticks.length.y = unit(7, "pt"),
    axis.text = element_text(size = 11, colour = "black", angle = 70, hjust = 1),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 16
    ),
    axis.title.y = element_text(
      margin = margin(r = 10),
      size = 16
    ),
    plot.margin = margin(15, 15, 10, 15)
  )

ggsave("../results/fig/robustness_similarity.tiff", bg = "white",  width = 12)
```

n# docs robustness check
```{r}
ggplot(df, aes(x = param, y = n)) +
  geom_boxplot() +
  geom_jitter(aes(color = run_name)) +
  scale_y_continuous(
    limits = c(80, 160),
    breaks = seq(80, 200, by = 20),
    expand = c(0, 0)
  ) +
  theme_minimal() +
  labs(
    x = "",
    y = "Number of documents",
    color = "Hyperparameter value"
  ) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.line = element_line(colour = "black", size = .8),
    axis.ticks = element_line(colour = "black", size = .8),
    axis.ticks.length.x = unit(5, "pt"),
    axis.ticks.length.y = unit(7, "pt"),
    axis.text = element_text(size = 11, colour = "black", angle = 70, hjust = 1),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 16
    ),
    axis.title.y = element_text(
      margin = margin(r = 10),
      size = 16
    ),
    plot.margin = margin(15, 15, 10, 15)
  )

ggsave("../results/fig/robustness_n.tiff", bg = "white",  width = 12, height = 6)
```

